/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductInput = IDL.Record({
  'skuCode' : IDL.Text,
  'nameEn' : IDL.Text,
  'nameFr' : IDL.Text,
  'nameKm' : IDL.Text,
  'descriptionEn' : IDL.Opt(IDL.Text),
  'descriptionFr' : IDL.Opt(IDL.Text),
  'descriptionKm' : IDL.Opt(IDL.Text),
  'baseCostKhr' : IDL.Nat,
  'retailPriceKhr' : IDL.Nat,
  'retailPriceUsd' : IDL.Float64,
  'commissionRatePercentage' : IDL.Float64,
  'championCommissionKhr' : IDL.Nat,
  'championCommissionUsd' : IDL.Float64,
  'wholesalePriceKhr' : IDL.Nat,
  'wholesalePriceUsd' : IDL.Float64,
  'unitMeasurement' : IDL.Text,
  'isActive' : IDL.Bool,
  'referralPriceKhr' : IDL.Opt(IDL.Nat),
  'referralPriceUsd' : IDL.Opt(IDL.Float64),
  'unitSize' : IDL.Float64,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const ApproveChampionInput = IDL.Record({
  'notesEn' : IDL.Opt(IDL.Text),
  'notesFr' : IDL.Opt(IDL.Text),
  'notesKm' : IDL.Opt(IDL.Text),
  'qrCodeImageUrl' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const ConsignmentInput = IDL.Record({
  'staffId' : IDL.Nat,
  'notesEn' : IDL.Opt(IDL.Text),
  'notesFr' : IDL.Opt(IDL.Text),
  'notesKm' : IDL.Opt(IDL.Text),
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'championId' : IDL.Nat,
});
export const ChampionSelectionMethod = IDL.Variant({
  'browsed_list' : IDL.Null,
  'staff_assigned' : IDL.Null,
  'remembered' : IDL.Null,
  'qr_scan' : IDL.Null,
});
export const OrderItemInput = IDL.Record({
  'championCommissionKhr' : IDL.Nat,
  'championCommissionUsd' : IDL.Float64,
  'productId' : IDL.Nat,
  'unitPriceKhr' : IDL.Nat,
  'unitPriceUsd' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const OrderInput = IDL.Record({
  'hotelSelectedChampionMethod' : ChampionSelectionMethod,
  'qrCodeUsed' : IDL.Opt(IDL.Text),
  'hotelId' : IDL.Nat,
  'staffProxyId' : IDL.Opt(IDL.Nat),
  'referralCodeUsed' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItemInput),
  'payoutCycleStartDate' : IDL.Text,
  'championId' : IDL.Nat,
  'payoutCycleEndDate' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'skuCode' : IDL.Text,
  'nameEn' : IDL.Text,
  'nameFr' : IDL.Text,
  'nameKm' : IDL.Text,
  'descriptionEn' : IDL.Opt(IDL.Text),
  'descriptionFr' : IDL.Opt(IDL.Text),
  'descriptionKm' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'baseCostKhr' : IDL.Nat,
  'retailPriceKhr' : IDL.Nat,
  'retailPriceUsd' : IDL.Float64,
  'commissionRatePercentage' : IDL.Float64,
  'championCommissionKhr' : IDL.Nat,
  'championCommissionUsd' : IDL.Float64,
  'wholesalePriceKhr' : IDL.Nat,
  'wholesalePriceUsd' : IDL.Float64,
  'unitMeasurement' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'referralPriceKhr' : IDL.Opt(IDL.Nat),
  'referralPriceUsd' : IDL.Opt(IDL.Float64),
  'unitSize' : IDL.Float64,
});
export const ChampionMetrics = IDL.Record({
  'sponsorCount' : IDL.Nat,
  'orderCount' : IDL.Nat,
  'bottlesSold' : IDL.Nat,
  'championId' : IDL.Nat,
  'totalEarningsKhr' : IDL.Nat,
  'totalEarningsUsd' : IDL.Float64,
});
export const PreferredLanguage = IDL.Variant({
  'en' : IDL.Null,
  'fr' : IDL.Null,
  'km' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'hotel' : IDL.Null,
  'staff' : IDL.Null,
  'champion' : IDL.Null,
});
export const OnboardingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'fullNameEn' : IDL.Text,
  'fullNameFr' : IDL.Opt(IDL.Text),
  'fullNameKm' : IDL.Opt(IDL.Text),
  'referralCodeActivatedAt' : IDL.Opt(IDL.Int),
  'referredById' : IDL.Opt(IDL.Nat),
  'preferredLanguage' : PreferredLanguage,
  'qrCodeActivatedAt' : IDL.Opt(IDL.Int),
  'physicalQrCodeId' : IDL.Opt(IDL.Text),
  'personalReferralCode' : IDL.Opt(IDL.Text),
  'approvedAt' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'onboardingNotesEn' : IDL.Opt(IDL.Text),
  'onboardingNotesFr' : IDL.Opt(IDL.Text),
  'onboardingNotesKm' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'approvedByStaffId' : IDL.Opt(IDL.Nat),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'onboardingStatus' : OnboardingStatus,
  'bioEn' : IDL.Opt(IDL.Text),
  'bioFr' : IDL.Opt(IDL.Text),
  'bioKm' : IDL.Opt(IDL.Text),
  'hasPaidForward' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'consignmentInventoryHeld' : IDL.Nat,
  'referredByCode' : IDL.Opt(IDL.Text),
  'targetMonthlyIncomeKhr' : IDL.Nat,
  'targetMonthlyIncomeUsd' : IDL.Nat,
});
export const ChampionCode = IDL.Record({
  'id' : IDL.Nat,
  'referralCode' : IDL.Text,
  'timesUsedForHotelOrders' : IDL.Nat,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'timesUsedForChampionReferrals' : IDL.Nat,
  'qrCodeId' : IDL.Text,
  'qrCodeImageUrl' : IDL.Opt(IDL.Text),
  'championId' : IDL.Nat,
});
export const ConsignmentStatus = IDL.Variant({
  'out' : IDL.Null,
  'sold' : IDL.Null,
  'returned' : IDL.Null,
});
export const ConsignmentCheckout = IDL.Record({
  'id' : IDL.Nat,
  'status' : ConsignmentStatus,
  'staffId' : IDL.Nat,
  'notesEn' : IDL.Opt(IDL.Text),
  'notesFr' : IDL.Opt(IDL.Text),
  'notesKm' : IDL.Opt(IDL.Text),
  'checkedOutAt' : IDL.Int,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'returnedAt' : IDL.Opt(IDL.Int),
  'championId' : IDL.Nat,
});
export const ImpactStats = IDL.Record({
  'totalCommunityEarningsKhr' : IDL.Nat,
  'localValueCirculatedKhr' : IDL.Nat,
  'championsEmpowered' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'id' : IDL.Nat,
  'championCommissionKhr' : IDL.Nat,
  'championCommissionUsd' : IDL.Float64,
  'productId' : IDL.Nat,
  'orderId' : IDL.Nat,
  'unitPriceKhr' : IDL.Nat,
  'unitPriceUsd' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'hotelSelectedChampionMethod' : ChampionSelectionMethod,
  'qrCodeUsed' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'hotelId' : IDL.Nat,
  'orderDate' : IDL.Int,
  'staffProxyId' : IDL.Opt(IDL.Nat),
  'referralCodeUsed' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'khqrReceiptHash' : IDL.Opt(IDL.Text),
  'khqrPaymentConfirmed' : IDL.Bool,
  'totalAmountKhr' : IDL.Nat,
  'totalAmountUsd' : IDL.Float64,
  'payoutProcessedDate' : IDL.Opt(IDL.Text),
  'payoutCycleStartDate' : IDL.Text,
  'biweeklyPayoutProcessed' : IDL.Bool,
  'championId' : IDL.Nat,
  'payoutCycleEndDate' : IDL.Text,
});
export const PayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PayoutMethod = IDL.Variant({
  'cash' : IDL.Null,
  'wing' : IDL.Null,
  'bank_transfer' : IDL.Null,
});
export const PayoutLedger = IDL.Record({
  'id' : IDL.Nat,
  'payoutStatus' : PayoutStatus,
  'payoutMethod' : PayoutMethod,
  'createdAt' : IDL.Int,
  'notesEn' : IDL.Opt(IDL.Text),
  'notesFr' : IDL.Opt(IDL.Text),
  'notesKm' : IDL.Opt(IDL.Text),
  'processedByStaffId' : IDL.Opt(IDL.Nat),
  'processedAt' : IDL.Opt(IDL.Int),
  'payoutCycleStart' : IDL.Text,
  'totalCommissionKhr' : IDL.Nat,
  'totalCommissionUsd' : IDL.Float64,
  'payoutCycleEnd' : IDL.Text,
  'totalOrdersCount' : IDL.Nat,
  'championId' : IDL.Nat,
});
export const Translation = IDL.Record({
  'en' : IDL.Text,
  'fr' : IDL.Text,
  'id' : IDL.Nat,
  'km' : IDL.Text,
  'key' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserRegistrationInput = IDL.Record({
  'fullNameEn' : IDL.Text,
  'fullNameFr' : IDL.Opt(IDL.Text),
  'fullNameKm' : IDL.Opt(IDL.Text),
  'preferredLanguage' : PreferredLanguage,
  'role' : UserRole,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'bioEn' : IDL.Opt(IDL.Text),
  'bioFr' : IDL.Opt(IDL.Text),
  'bioKm' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
  'referredByCode' : IDL.Opt(IDL.Text),
});
export const UserUpdateInput = IDL.Record({
  'fullNameEn' : IDL.Opt(IDL.Text),
  'fullNameFr' : IDL.Opt(IDL.Text),
  'fullNameKm' : IDL.Opt(IDL.Text),
  'preferredLanguage' : IDL.Opt(PreferredLanguage),
  'isActive' : IDL.Opt(IDL.Bool),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'bioEn' : IDL.Opt(IDL.Text),
  'bioFr' : IDL.Opt(IDL.Text),
  'bioKm' : IDL.Opt(IDL.Text),
  'hasPaidForward' : IDL.Opt(IDL.Bool),
  'targetMonthlyIncomeKhr' : IDL.Opt(IDL.Nat),
  'targetMonthlyIncomeUsd' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([ProductInput], [Result_1], []),
  'approveChampion' : IDL.Func([IDL.Nat, ApproveChampionInput], [Result], []),
  'checkoutConsignment' : IDL.Func([ConsignmentInput], [Result_1], []),
  'confirmPayment' : IDL.Func([IDL.Nat], [Result], []),
  'createOrder' : IDL.Func([OrderInput], [Result_1], []),
  'generatePayoutLedger' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], []),
  'getAllChampionMetrics' : IDL.Func([], [IDL.Vec(ChampionMetrics)], ['query']),
  'getApprovedChampions' : IDL.Func([], [IDL.Vec(User)], []),
  'getCallerPrincipal' : IDL.Func([], [IDL.Text], []),
  'getChampionCodes' : IDL.Func([IDL.Nat], [IDL.Vec(ChampionCode)], []),
  'getChampionMetrics' : IDL.Func([IDL.Nat], [ChampionMetrics], ['query']),
  'getConsignmentByChampion' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ConsignmentCheckout)],
      [],
    ),
  'getImpactStats' : IDL.Func([], [ImpactStats], []),
  'getOrderItems' : IDL.Func([IDL.Nat], [IDL.Vec(OrderItem)], []),
  'getOrdersByChampion' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], []),
  'getOrdersByHotel' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], []),
  'getPendingChampions' : IDL.Func([], [IDL.Vec(User)], []),
  'getPendingPayouts' : IDL.Func([], [IDL.Vec(PayoutLedger)], []),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
  'getTranslationByKey' : IDL.Func([IDL.Text], [IDL.Opt(Translation)], []),
  'getTranslations' : IDL.Func([], [IDL.Vec(Translation)], []),
  'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], []),
  'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(User)], []),
  'markPayoutProcessed' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
  'regenerateChampionQR' : IDL.Func([IDL.Nat], [Result_2], []),
  'registerUser' : IDL.Func([UserRegistrationInput], [Result_1], []),
  'rejectChampion' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'updateUser' : IDL.Func([IDL.Nat, UserUpdateInput], [Result], []),
  'validateReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(ChampionCode)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductInput = IDL.Record({
    'skuCode' : IDL.Text,
    'nameEn' : IDL.Text,
    'nameFr' : IDL.Text,
    'nameKm' : IDL.Text,
    'descriptionEn' : IDL.Opt(IDL.Text),
    'descriptionFr' : IDL.Opt(IDL.Text),
    'descriptionKm' : IDL.Opt(IDL.Text),
    'baseCostKhr' : IDL.Nat,
    'retailPriceKhr' : IDL.Nat,
    'retailPriceUsd' : IDL.Float64,
    'commissionRatePercentage' : IDL.Float64,
    'championCommissionKhr' : IDL.Nat,
    'championCommissionUsd' : IDL.Float64,
    'wholesalePriceKhr' : IDL.Nat,
    'wholesalePriceUsd' : IDL.Float64,
    'unitMeasurement' : IDL.Text,
    'isActive' : IDL.Bool,
    'referralPriceKhr' : IDL.Opt(IDL.Nat),
    'referralPriceUsd' : IDL.Opt(IDL.Float64),
    'unitSize' : IDL.Float64,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const ApproveChampionInput = IDL.Record({
    'notesEn' : IDL.Opt(IDL.Text),
    'notesFr' : IDL.Opt(IDL.Text),
    'notesKm' : IDL.Opt(IDL.Text),
    'qrCodeImageUrl' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const ConsignmentInput = IDL.Record({
    'staffId' : IDL.Nat,
    'notesEn' : IDL.Opt(IDL.Text),
    'notesFr' : IDL.Opt(IDL.Text),
    'notesKm' : IDL.Opt(IDL.Text),
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'championId' : IDL.Nat,
  });
  const ChampionSelectionMethod = IDL.Variant({
    'browsed_list' : IDL.Null,
    'staff_assigned' : IDL.Null,
    'remembered' : IDL.Null,
    'qr_scan' : IDL.Null,
  });
  const OrderItemInput = IDL.Record({
    'championCommissionKhr' : IDL.Nat,
    'championCommissionUsd' : IDL.Float64,
    'productId' : IDL.Nat,
    'unitPriceKhr' : IDL.Nat,
    'unitPriceUsd' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const OrderInput = IDL.Record({
    'hotelSelectedChampionMethod' : ChampionSelectionMethod,
    'qrCodeUsed' : IDL.Opt(IDL.Text),
    'hotelId' : IDL.Nat,
    'staffProxyId' : IDL.Opt(IDL.Nat),
    'referralCodeUsed' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItemInput),
    'payoutCycleStartDate' : IDL.Text,
    'championId' : IDL.Nat,
    'payoutCycleEndDate' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'skuCode' : IDL.Text,
    'nameEn' : IDL.Text,
    'nameFr' : IDL.Text,
    'nameKm' : IDL.Text,
    'descriptionEn' : IDL.Opt(IDL.Text),
    'descriptionFr' : IDL.Opt(IDL.Text),
    'descriptionKm' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'baseCostKhr' : IDL.Nat,
    'retailPriceKhr' : IDL.Nat,
    'retailPriceUsd' : IDL.Float64,
    'commissionRatePercentage' : IDL.Float64,
    'championCommissionKhr' : IDL.Nat,
    'championCommissionUsd' : IDL.Float64,
    'wholesalePriceKhr' : IDL.Nat,
    'wholesalePriceUsd' : IDL.Float64,
    'unitMeasurement' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'referralPriceKhr' : IDL.Opt(IDL.Nat),
    'referralPriceUsd' : IDL.Opt(IDL.Float64),
    'unitSize' : IDL.Float64,
  });
  const ChampionMetrics = IDL.Record({
    'sponsorCount' : IDL.Nat,
    'orderCount' : IDL.Nat,
    'bottlesSold' : IDL.Nat,
    'championId' : IDL.Nat,
    'totalEarningsKhr' : IDL.Nat,
    'totalEarningsUsd' : IDL.Float64,
  });
  const PreferredLanguage = IDL.Variant({
    'en' : IDL.Null,
    'fr' : IDL.Null,
    'km' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'hotel' : IDL.Null,
    'staff' : IDL.Null,
    'champion' : IDL.Null,
  });
  const OnboardingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'fullNameEn' : IDL.Text,
    'fullNameFr' : IDL.Opt(IDL.Text),
    'fullNameKm' : IDL.Opt(IDL.Text),
    'referralCodeActivatedAt' : IDL.Opt(IDL.Int),
    'referredById' : IDL.Opt(IDL.Nat),
    'preferredLanguage' : PreferredLanguage,
    'qrCodeActivatedAt' : IDL.Opt(IDL.Int),
    'physicalQrCodeId' : IDL.Opt(IDL.Text),
    'personalReferralCode' : IDL.Opt(IDL.Text),
    'approvedAt' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'onboardingNotesEn' : IDL.Opt(IDL.Text),
    'onboardingNotesFr' : IDL.Opt(IDL.Text),
    'onboardingNotesKm' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'approvedByStaffId' : IDL.Opt(IDL.Nat),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'onboardingStatus' : OnboardingStatus,
    'bioEn' : IDL.Opt(IDL.Text),
    'bioFr' : IDL.Opt(IDL.Text),
    'bioKm' : IDL.Opt(IDL.Text),
    'hasPaidForward' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'consignmentInventoryHeld' : IDL.Nat,
    'referredByCode' : IDL.Opt(IDL.Text),
    'targetMonthlyIncomeKhr' : IDL.Nat,
    'targetMonthlyIncomeUsd' : IDL.Nat,
  });
  const ChampionCode = IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'timesUsedForHotelOrders' : IDL.Nat,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'timesUsedForChampionReferrals' : IDL.Nat,
    'qrCodeId' : IDL.Text,
    'qrCodeImageUrl' : IDL.Opt(IDL.Text),
    'championId' : IDL.Nat,
  });
  const ConsignmentStatus = IDL.Variant({
    'out' : IDL.Null,
    'sold' : IDL.Null,
    'returned' : IDL.Null,
  });
  const ConsignmentCheckout = IDL.Record({
    'id' : IDL.Nat,
    'status' : ConsignmentStatus,
    'staffId' : IDL.Nat,
    'notesEn' : IDL.Opt(IDL.Text),
    'notesFr' : IDL.Opt(IDL.Text),
    'notesKm' : IDL.Opt(IDL.Text),
    'checkedOutAt' : IDL.Int,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'returnedAt' : IDL.Opt(IDL.Int),
    'championId' : IDL.Nat,
  });
  const ImpactStats = IDL.Record({
    'totalCommunityEarningsKhr' : IDL.Nat,
    'localValueCirculatedKhr' : IDL.Nat,
    'championsEmpowered' : IDL.Nat,
  });
  const OrderItem = IDL.Record({
    'id' : IDL.Nat,
    'championCommissionKhr' : IDL.Nat,
    'championCommissionUsd' : IDL.Float64,
    'productId' : IDL.Nat,
    'orderId' : IDL.Nat,
    'unitPriceKhr' : IDL.Nat,
    'unitPriceUsd' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'hotelSelectedChampionMethod' : ChampionSelectionMethod,
    'qrCodeUsed' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'hotelId' : IDL.Nat,
    'orderDate' : IDL.Int,
    'staffProxyId' : IDL.Opt(IDL.Nat),
    'referralCodeUsed' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'khqrReceiptHash' : IDL.Opt(IDL.Text),
    'khqrPaymentConfirmed' : IDL.Bool,
    'totalAmountKhr' : IDL.Nat,
    'totalAmountUsd' : IDL.Float64,
    'payoutProcessedDate' : IDL.Opt(IDL.Text),
    'payoutCycleStartDate' : IDL.Text,
    'biweeklyPayoutProcessed' : IDL.Bool,
    'championId' : IDL.Nat,
    'payoutCycleEndDate' : IDL.Text,
  });
  const PayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PayoutMethod = IDL.Variant({
    'cash' : IDL.Null,
    'wing' : IDL.Null,
    'bank_transfer' : IDL.Null,
  });
  const PayoutLedger = IDL.Record({
    'id' : IDL.Nat,
    'payoutStatus' : PayoutStatus,
    'payoutMethod' : PayoutMethod,
    'createdAt' : IDL.Int,
    'notesEn' : IDL.Opt(IDL.Text),
    'notesFr' : IDL.Opt(IDL.Text),
    'notesKm' : IDL.Opt(IDL.Text),
    'processedByStaffId' : IDL.Opt(IDL.Nat),
    'processedAt' : IDL.Opt(IDL.Int),
    'payoutCycleStart' : IDL.Text,
    'totalCommissionKhr' : IDL.Nat,
    'totalCommissionUsd' : IDL.Float64,
    'payoutCycleEnd' : IDL.Text,
    'totalOrdersCount' : IDL.Nat,
    'championId' : IDL.Nat,
  });
  const Translation = IDL.Record({
    'en' : IDL.Text,
    'fr' : IDL.Text,
    'id' : IDL.Nat,
    'km' : IDL.Text,
    'key' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRegistrationInput = IDL.Record({
    'fullNameEn' : IDL.Text,
    'fullNameFr' : IDL.Opt(IDL.Text),
    'fullNameKm' : IDL.Opt(IDL.Text),
    'preferredLanguage' : PreferredLanguage,
    'role' : UserRole,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'bioEn' : IDL.Opt(IDL.Text),
    'bioFr' : IDL.Opt(IDL.Text),
    'bioKm' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
    'referredByCode' : IDL.Opt(IDL.Text),
  });
  const UserUpdateInput = IDL.Record({
    'fullNameEn' : IDL.Opt(IDL.Text),
    'fullNameFr' : IDL.Opt(IDL.Text),
    'fullNameKm' : IDL.Opt(IDL.Text),
    'preferredLanguage' : IDL.Opt(PreferredLanguage),
    'isActive' : IDL.Opt(IDL.Bool),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'bioEn' : IDL.Opt(IDL.Text),
    'bioFr' : IDL.Opt(IDL.Text),
    'bioKm' : IDL.Opt(IDL.Text),
    'hasPaidForward' : IDL.Opt(IDL.Bool),
    'targetMonthlyIncomeKhr' : IDL.Opt(IDL.Nat),
    'targetMonthlyIncomeUsd' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([ProductInput], [Result_1], []),
    'approveChampion' : IDL.Func([IDL.Nat, ApproveChampionInput], [Result], []),
    'checkoutConsignment' : IDL.Func([ConsignmentInput], [Result_1], []),
    'confirmPayment' : IDL.Func([IDL.Nat], [Result], []),
    'createOrder' : IDL.Func([OrderInput], [Result_1], []),
    'generatePayoutLedger' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], []),
    'getAllChampionMetrics' : IDL.Func(
        [],
        [IDL.Vec(ChampionMetrics)],
        ['query'],
      ),
    'getApprovedChampions' : IDL.Func([], [IDL.Vec(User)], []),
    'getCallerPrincipal' : IDL.Func([], [IDL.Text], []),
    'getChampionCodes' : IDL.Func([IDL.Nat], [IDL.Vec(ChampionCode)], []),
    'getChampionMetrics' : IDL.Func([IDL.Nat], [ChampionMetrics], ['query']),
    'getConsignmentByChampion' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ConsignmentCheckout)],
        [],
      ),
    'getImpactStats' : IDL.Func([], [ImpactStats], []),
    'getOrderItems' : IDL.Func([IDL.Nat], [IDL.Vec(OrderItem)], []),
    'getOrdersByChampion' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], []),
    'getOrdersByHotel' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], []),
    'getPendingChampions' : IDL.Func([], [IDL.Vec(User)], []),
    'getPendingPayouts' : IDL.Func([], [IDL.Vec(PayoutLedger)], []),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
    'getTranslationByKey' : IDL.Func([IDL.Text], [IDL.Opt(Translation)], []),
    'getTranslations' : IDL.Func([], [IDL.Vec(Translation)], []),
    'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], []),
    'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(User)], []),
    'markPayoutProcessed' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
    'regenerateChampionQR' : IDL.Func([IDL.Nat], [Result_2], []),
    'registerUser' : IDL.Func([UserRegistrationInput], [Result_1], []),
    'rejectChampion' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'updateUser' : IDL.Func([IDL.Nat, UserUpdateInput], [Result], []),
    'validateReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(ChampionCode)], []),
  });
};

export const init = ({ IDL }) => { return []; };