/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApproveChampionInput {
  'notesEn' : [] | [string],
  'notesFr' : [] | [string],
  'notesKm' : [] | [string],
  'qrCodeImageUrl' : [] | [string],
}
export interface ChampionCode {
  'id' : bigint,
  'referralCode' : string,
  'timesUsedForHotelOrders' : bigint,
  'createdAt' : bigint,
  'isActive' : boolean,
  'timesUsedForChampionReferrals' : bigint,
  'qrCodeId' : string,
  'qrCodeImageUrl' : [] | [string],
  'championId' : bigint,
}
export interface ChampionMetrics {
  'sponsorCount' : bigint,
  'orderCount' : bigint,
  'bottlesSold' : bigint,
  'championId' : bigint,
  'totalEarningsKhr' : bigint,
  'totalEarningsUsd' : number,
}
export type ChampionSelectionMethod = { 'browsed_list' : null } |
  { 'staff_assigned' : null } |
  { 'remembered' : null } |
  { 'qr_scan' : null };
export interface ConsignmentCheckout {
  'id' : bigint,
  'status' : ConsignmentStatus,
  'staffId' : bigint,
  'notesEn' : [] | [string],
  'notesFr' : [] | [string],
  'notesKm' : [] | [string],
  'checkedOutAt' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
  'returnedAt' : [] | [bigint],
  'championId' : bigint,
}
export interface ConsignmentInput {
  'staffId' : bigint,
  'notesEn' : [] | [string],
  'notesFr' : [] | [string],
  'notesKm' : [] | [string],
  'productId' : bigint,
  'quantity' : bigint,
  'championId' : bigint,
}
export type ConsignmentStatus = { 'out' : null } |
  { 'sold' : null } |
  { 'returned' : null };
export interface ImpactStats {
  'totalCommunityEarningsKhr' : bigint,
  'localValueCirculatedKhr' : bigint,
  'championsEmpowered' : bigint,
}
export type OnboardingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Order {
  'id' : bigint,
  'hotelSelectedChampionMethod' : ChampionSelectionMethod,
  'qrCodeUsed' : [] | [string],
  'createdAt' : bigint,
  'hotelId' : bigint,
  'orderDate' : bigint,
  'staffProxyId' : [] | [bigint],
  'referralCodeUsed' : [] | [string],
  'updatedAt' : bigint,
  'khqrReceiptHash' : [] | [string],
  'khqrPaymentConfirmed' : boolean,
  'totalAmountKhr' : bigint,
  'totalAmountUsd' : number,
  'payoutProcessedDate' : [] | [string],
  'payoutCycleStartDate' : string,
  'biweeklyPayoutProcessed' : boolean,
  'championId' : bigint,
  'payoutCycleEndDate' : string,
}
export interface OrderInput {
  'hotelSelectedChampionMethod' : ChampionSelectionMethod,
  'qrCodeUsed' : [] | [string],
  'hotelId' : bigint,
  'staffProxyId' : [] | [bigint],
  'referralCodeUsed' : [] | [string],
  'items' : Array<OrderItemInput>,
  'payoutCycleStartDate' : string,
  'championId' : bigint,
  'payoutCycleEndDate' : string,
}
export interface OrderItem {
  'id' : bigint,
  'championCommissionKhr' : bigint,
  'championCommissionUsd' : number,
  'productId' : bigint,
  'orderId' : bigint,
  'unitPriceKhr' : bigint,
  'unitPriceUsd' : number,
  'quantity' : bigint,
}
export interface OrderItemInput {
  'championCommissionKhr' : bigint,
  'championCommissionUsd' : number,
  'productId' : bigint,
  'unitPriceKhr' : bigint,
  'unitPriceUsd' : number,
  'quantity' : bigint,
}
export interface PayoutLedger {
  'id' : bigint,
  'payoutStatus' : PayoutStatus,
  'payoutMethod' : PayoutMethod,
  'createdAt' : bigint,
  'notesEn' : [] | [string],
  'notesFr' : [] | [string],
  'notesKm' : [] | [string],
  'processedByStaffId' : [] | [bigint],
  'processedAt' : [] | [bigint],
  'payoutCycleStart' : string,
  'totalCommissionKhr' : bigint,
  'totalCommissionUsd' : number,
  'payoutCycleEnd' : string,
  'totalOrdersCount' : bigint,
  'championId' : bigint,
}
export type PayoutMethod = { 'cash' : null } |
  { 'wing' : null } |
  { 'bank_transfer' : null };
export type PayoutStatus = { 'pending' : null } |
  { 'processed' : null } |
  { 'failed' : null };
export type PreferredLanguage = { 'en' : null } |
  { 'fr' : null } |
  { 'km' : null };
export interface Product {
  'id' : bigint,
  'skuCode' : string,
  'nameEn' : string,
  'nameFr' : string,
  'nameKm' : string,
  'descriptionEn' : [] | [string],
  'descriptionFr' : [] | [string],
  'descriptionKm' : [] | [string],
  'createdAt' : bigint,
  'baseCostKhr' : bigint,
  'retailPriceKhr' : bigint,
  'retailPriceUsd' : number,
  'commissionRatePercentage' : number,
  'championCommissionKhr' : bigint,
  'championCommissionUsd' : number,
  'wholesalePriceKhr' : bigint,
  'wholesalePriceUsd' : number,
  'unitMeasurement' : string,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'referralPriceKhr' : [] | [bigint],
  'referralPriceUsd' : [] | [number],
  'unitSize' : number,
}
export interface ProductInput {
  'skuCode' : string,
  'nameEn' : string,
  'nameFr' : string,
  'nameKm' : string,
  'descriptionEn' : [] | [string],
  'descriptionFr' : [] | [string],
  'descriptionKm' : [] | [string],
  'baseCostKhr' : bigint,
  'retailPriceKhr' : bigint,
  'retailPriceUsd' : number,
  'commissionRatePercentage' : number,
  'championCommissionKhr' : bigint,
  'championCommissionUsd' : number,
  'wholesalePriceKhr' : bigint,
  'wholesalePriceUsd' : number,
  'unitMeasurement' : string,
  'isActive' : boolean,
  'referralPriceKhr' : [] | [bigint],
  'referralPriceUsd' : [] | [number],
  'unitSize' : number,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_2 = { 'ok' : string } |
  { 'err' : string };
export interface Translation {
  'en' : string,
  'fr' : string,
  'id' : bigint,
  'km' : string,
  'key' : string,
  'createdAt' : bigint,
}
export interface User {
  'id' : bigint,
  'fullNameEn' : string,
  'fullNameFr' : [] | [string],
  'fullNameKm' : [] | [string],
  'referralCodeActivatedAt' : [] | [bigint],
  'referredById' : [] | [bigint],
  'preferredLanguage' : PreferredLanguage,
  'qrCodeActivatedAt' : [] | [bigint],
  'physicalQrCodeId' : [] | [string],
  'personalReferralCode' : [] | [string],
  'approvedAt' : [] | [bigint],
  'createdAt' : bigint,
  'role' : UserRole,
  'isActive' : boolean,
  'onboardingNotesEn' : [] | [string],
  'onboardingNotesFr' : [] | [string],
  'onboardingNotesKm' : [] | [string],
  'updatedAt' : bigint,
  'approvedByStaffId' : [] | [bigint],
  'avatarUrl' : [] | [string],
  'onboardingStatus' : OnboardingStatus,
  'bioEn' : [] | [string],
  'bioFr' : [] | [string],
  'bioKm' : [] | [string],
  'hasPaidForward' : boolean,
  'phoneNumber' : string,
  'consignmentInventoryHeld' : bigint,
  'referredByCode' : [] | [string],
  'targetMonthlyIncomeKhr' : bigint,
  'targetMonthlyIncomeUsd' : bigint,
}
export interface UserRegistrationInput {
  'fullNameEn' : string,
  'fullNameFr' : [] | [string],
  'fullNameKm' : [] | [string],
  'preferredLanguage' : PreferredLanguage,
  'role' : UserRole,
  'avatarUrl' : [] | [string],
  'bioEn' : [] | [string],
  'bioFr' : [] | [string],
  'bioKm' : [] | [string],
  'phoneNumber' : string,
  'referredByCode' : [] | [string],
}
export type UserRole = { 'hotel' : null } |
  { 'staff' : null } |
  { 'champion' : null };
export interface UserUpdateInput {
  'fullNameEn' : [] | [string],
  'fullNameFr' : [] | [string],
  'fullNameKm' : [] | [string],
  'preferredLanguage' : [] | [PreferredLanguage],
  'isActive' : [] | [boolean],
  'avatarUrl' : [] | [string],
  'bioEn' : [] | [string],
  'bioFr' : [] | [string],
  'bioKm' : [] | [string],
  'hasPaidForward' : [] | [boolean],
  'targetMonthlyIncomeKhr' : [] | [bigint],
  'targetMonthlyIncomeUsd' : [] | [bigint],
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[ProductInput], Result_1>,
  'approveChampion' : ActorMethod<[bigint, ApproveChampionInput], Result>,
  'checkoutConsignment' : ActorMethod<[ConsignmentInput], Result_1>,
  'confirmPayment' : ActorMethod<[bigint], Result>,
  'createOrder' : ActorMethod<[OrderInput], Result_1>,
  'generatePayoutLedger' : ActorMethod<[string, string], Result>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllChampionMetrics' : ActorMethod<[], Array<ChampionMetrics>>,
  'getApprovedChampions' : ActorMethod<[], Array<User>>,
  'getCallerPrincipal' : ActorMethod<[], string>,
  'getChampionCodes' : ActorMethod<[bigint], Array<ChampionCode>>,
  'getChampionMetrics' : ActorMethod<[bigint], ChampionMetrics>,
  'getConsignmentByChampion' : ActorMethod<
    [bigint],
    Array<ConsignmentCheckout>
  >,
  'getImpactStats' : ActorMethod<[], ImpactStats>,
  'getOrderItems' : ActorMethod<[bigint], Array<OrderItem>>,
  'getOrdersByChampion' : ActorMethod<[bigint], Array<Order>>,
  'getOrdersByHotel' : ActorMethod<[bigint], Array<Order>>,
  'getPendingChampions' : ActorMethod<[], Array<User>>,
  'getPendingPayouts' : ActorMethod<[], Array<PayoutLedger>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getTranslationByKey' : ActorMethod<[string], [] | [Translation]>,
  'getTranslations' : ActorMethod<[], Array<Translation>>,
  'getUserById' : ActorMethod<[bigint], [] | [User]>,
  'getUserByPhone' : ActorMethod<[string], [] | [User]>,
  'markPayoutProcessed' : ActorMethod<[bigint, bigint], Result>,
  'regenerateChampionQR' : ActorMethod<[bigint], Result_2>,
  'registerUser' : ActorMethod<[UserRegistrationInput], Result_1>,
  'rejectChampion' : ActorMethod<[bigint, string], Result>,
  'updateUser' : ActorMethod<[bigint, UserUpdateInput], Result>,
  'validateReferralCode' : ActorMethod<[string], [] | [ChampionCode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];