/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductInput {
    skuCode: string;
    nameEn: string;
    nameFr: string;
    nameKm: string;
    descriptionEn?: string;
    descriptionFr?: string;
    descriptionKm?: string;
    baseCostKhr: bigint;
    retailPriceKhr: bigint;
    retailPriceUsd: number;
    commissionRatePercentage: number;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    wholesalePriceKhr: bigint;
    wholesalePriceUsd: number;
    unitMeasurement: string;
    isActive: boolean;
    referralPriceKhr?: bigint;
    referralPriceUsd?: number;
    unitSize: number;
}
export type Result_2 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Translation {
    en: string;
    fr: string;
    id: bigint;
    km: string;
    key: string;
    createdAt: bigint;
}
export interface User {
    id: bigint;
    fullNameEn: string;
    fullNameFr?: string;
    fullNameKm?: string;
    referralCodeActivatedAt?: bigint;
    referredById?: bigint;
    preferredLanguage: PreferredLanguage;
    qrCodeActivatedAt?: bigint;
    physicalQrCodeId?: string;
    personalReferralCode?: string;
    approvedAt?: bigint;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    onboardingNotesEn?: string;
    onboardingNotesFr?: string;
    onboardingNotesKm?: string;
    updatedAt: bigint;
    approvedByStaffId?: bigint;
    avatarUrl?: string;
    onboardingStatus: OnboardingStatus;
    bioEn?: string;
    bioFr?: string;
    bioKm?: string;
    hasPaidForward: boolean;
    phoneNumber: string;
    consignmentInventoryHeld: bigint;
    referredByCode?: string;
    targetMonthlyIncomeKhr: bigint;
    targetMonthlyIncomeUsd: bigint;
}
export interface PayoutLedger {
    id: bigint;
    payoutStatus: PayoutStatus;
    payoutMethod: PayoutMethod;
    createdAt: bigint;
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    processedByStaffId?: bigint;
    processedAt?: bigint;
    payoutCycleStart: string;
    totalCommissionKhr: bigint;
    totalCommissionUsd: number;
    payoutCycleEnd: string;
    totalOrdersCount: bigint;
    championId: bigint;
}
export interface OrderItem {
    id: bigint;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    productId: bigint;
    orderId: bigint;
    unitPriceKhr: bigint;
    unitPriceUsd: number;
    quantity: bigint;
}
export interface OrderItemInput {
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    productId: bigint;
    unitPriceKhr: bigint;
    unitPriceUsd: number;
    quantity: bigint;
}
export interface OrderInput {
    hotelSelectedChampionMethod: ChampionSelectionMethod;
    qrCodeUsed?: string;
    hotelId: bigint;
    staffProxyId?: bigint;
    referralCodeUsed?: string;
    items: Array<OrderItemInput>;
    payoutCycleStartDate: string;
    championId: bigint;
    payoutCycleEndDate: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface Order {
    id: bigint;
    hotelSelectedChampionMethod: ChampionSelectionMethod;
    qrCodeUsed?: string;
    createdAt: bigint;
    hotelId: bigint;
    orderDate: bigint;
    staffProxyId?: bigint;
    referralCodeUsed?: string;
    updatedAt: bigint;
    khqrReceiptHash?: string;
    khqrPaymentConfirmed: boolean;
    totalAmountKhr: bigint;
    totalAmountUsd: number;
    payoutProcessedDate?: string;
    payoutCycleStartDate: string;
    biweeklyPayoutProcessed: boolean;
    championId: bigint;
    payoutCycleEndDate: string;
}
export interface UserUpdateInput {
    fullNameEn?: string;
    fullNameFr?: string;
    fullNameKm?: string;
    preferredLanguage?: PreferredLanguage;
    isActive?: boolean;
    avatarUrl?: string;
    bioEn?: string;
    bioFr?: string;
    bioKm?: string;
    hasPaidForward?: boolean;
    targetMonthlyIncomeKhr?: bigint;
    targetMonthlyIncomeUsd?: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface ChampionMetrics {
    sponsorCount: bigint;
    orderCount: bigint;
    bottlesSold: bigint;
    championId: bigint;
    totalEarningsKhr: bigint;
    totalEarningsUsd: number;
}
export interface ApproveChampionInput {
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    qrCodeImageUrl?: string;
}
export interface UserRegistrationInput {
    fullNameEn: string;
    fullNameFr?: string;
    fullNameKm?: string;
    preferredLanguage: PreferredLanguage;
    role: UserRole;
    avatarUrl?: string;
    bioEn?: string;
    bioFr?: string;
    bioKm?: string;
    phoneNumber: string;
    referredByCode?: string;
}
export interface ConsignmentInput {
    staffId: bigint;
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    productId: bigint;
    quantity: bigint;
    championId: bigint;
}
export interface ImpactStats {
    totalCommunityEarningsKhr: bigint;
    localValueCirculatedKhr: bigint;
    championsEmpowered: bigint;
}
export interface ChampionCode {
    id: bigint;
    referralCode: string;
    timesUsedForHotelOrders: bigint;
    createdAt: bigint;
    isActive: boolean;
    timesUsedForChampionReferrals: bigint;
    qrCodeId: string;
    qrCodeImageUrl?: string;
    championId: bigint;
}
export interface Product {
    id: bigint;
    skuCode: string;
    nameEn: string;
    nameFr: string;
    nameKm: string;
    descriptionEn?: string;
    descriptionFr?: string;
    descriptionKm?: string;
    createdAt: bigint;
    baseCostKhr: bigint;
    retailPriceKhr: bigint;
    retailPriceUsd: number;
    commissionRatePercentage: number;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    wholesalePriceKhr: bigint;
    wholesalePriceUsd: number;
    unitMeasurement: string;
    isActive: boolean;
    updatedAt: bigint;
    referralPriceKhr?: bigint;
    referralPriceUsd?: number;
    unitSize: number;
}
export interface ConsignmentCheckout {
    id: bigint;
    status: ConsignmentStatus;
    staffId: bigint;
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    checkedOutAt: bigint;
    productId: bigint;
    quantity: bigint;
    returnedAt?: bigint;
    championId: bigint;
}
export enum ChampionSelectionMethod {
    browsed_list = "browsed_list",
    staff_assigned = "staff_assigned",
    remembered = "remembered",
    qr_scan = "qr_scan"
}
export enum ConsignmentStatus {
    out = "out",
    sold = "sold",
    returned = "returned"
}
export enum OnboardingStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum PayoutMethod {
    cash = "cash",
    wing = "wing",
    bank_transfer = "bank_transfer"
}
export enum PayoutStatus {
    pending = "pending",
    processed = "processed",
    failed = "failed"
}
export enum PreferredLanguage {
    en = "en",
    fr = "fr",
    km = "km"
}
export enum UserRole {
    hotel = "hotel",
    staff = "staff",
    champion = "champion"
}
export interface backendInterface {
    addProduct(input: ProductInput): Promise<Result_1>;
    approveChampion(userId: bigint, input: ApproveChampionInput): Promise<Result>;
    checkoutConsignment(input: ConsignmentInput): Promise<Result_1>;
    confirmPayment(orderId: bigint): Promise<Result>;
    createOrder(input: OrderInput): Promise<Result_1>;
    generatePayoutLedger(cycleStart: string, cycleEnd: string): Promise<Result>;
    getActiveProducts(): Promise<Array<Product>>;
    getAllChampionMetrics(): Promise<Array<ChampionMetrics>>;
    getApprovedChampions(): Promise<Array<User>>;
    getCallerPrincipal(): Promise<string>;
    getChampionCodes(championId: bigint): Promise<Array<ChampionCode>>;
    getChampionMetrics(championId: bigint): Promise<ChampionMetrics>;
    getConsignmentByChampion(championId: bigint): Promise<Array<ConsignmentCheckout>>;
    getImpactStats(): Promise<ImpactStats>;
    getOrderItems(orderId: bigint): Promise<Array<OrderItem>>;
    getOrdersByChampion(championId: bigint): Promise<Array<Order>>;
    getOrdersByHotel(hotelId: bigint): Promise<Array<Order>>;
    getPendingChampions(): Promise<Array<User>>;
    getPendingPayouts(): Promise<Array<PayoutLedger>>;
    getProducts(): Promise<Array<Product>>;
    getTranslationByKey(key: string): Promise<Translation | null>;
    getTranslations(): Promise<Array<Translation>>;
    getUserById(id: bigint): Promise<User | null>;
    getUserByPhone(phone: string): Promise<User | null>;
    markPayoutProcessed(payoutId: bigint, staffId: bigint): Promise<Result>;
    regenerateChampionQR(championId: bigint): Promise<Result_2>;
    registerUser(input: UserRegistrationInput): Promise<Result_1>;
    rejectChampion(userId: bigint, reason: string): Promise<Result>;
    updateUser(userId: bigint, input: UserUpdateInput): Promise<Result>;
    validateReferralCode(code: string): Promise<ChampionCode | null>;
}
import type { ApproveChampionInput as _ApproveChampionInput, ChampionCode as _ChampionCode, ChampionSelectionMethod as _ChampionSelectionMethod, ConsignmentCheckout as _ConsignmentCheckout, ConsignmentInput as _ConsignmentInput, ConsignmentStatus as _ConsignmentStatus, OnboardingStatus as _OnboardingStatus, Order as _Order, OrderInput as _OrderInput, OrderItemInput as _OrderItemInput, PayoutLedger as _PayoutLedger, PayoutMethod as _PayoutMethod, PayoutStatus as _PayoutStatus, PreferredLanguage as _PreferredLanguage, Product as _Product, ProductInput as _ProductInput, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Translation as _Translation, User as _User, UserRegistrationInput as _UserRegistrationInput, UserRole as _UserRole, UserUpdateInput as _UserUpdateInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: ProductInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveChampion(arg0: bigint, arg1: ApproveChampionInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.approveChampion(arg0, to_candid_ApproveChampionInput_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveChampion(arg0, to_candid_ApproveChampionInput_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkoutConsignment(arg0: ConsignmentInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutConsignment(to_candid_ConsignmentInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutConsignment(to_candid_ConsignmentInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmPayment(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: OrderInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async generatePayoutLedger(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePayoutLedger(arg0, arg1);
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePayoutLedger(arg0, arg1);
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProducts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProducts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChampionMetrics(): Promise<Array<ChampionMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChampionMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChampionMetrics();
            return result;
        }
    }
    async getApprovedChampions(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedChampions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedChampions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipal();
            return result;
        }
    }
    async getChampionCodes(arg0: bigint): Promise<Array<ChampionCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChampionCodes(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChampionCodes(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChampionMetrics(arg0: bigint): Promise<ChampionMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getChampionMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChampionMetrics(arg0);
            return result;
        }
    }
    async getConsignmentByChampion(arg0: bigint): Promise<Array<ConsignmentCheckout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsignmentByChampion(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsignmentByChampion(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImpactStats(): Promise<ImpactStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getImpactStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImpactStats();
            return result;
        }
    }
    async getOrderItems(arg0: bigint): Promise<Array<OrderItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderItems(arg0);
            return result;
        }
    }
    async getOrdersByChampion(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByChampion(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByChampion(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByHotel(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByHotel(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByHotel(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingChampions(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingChampions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingChampions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPayouts(): Promise<Array<PayoutLedger>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPayouts();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPayouts();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTranslationByKey(arg0: string): Promise<Translation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTranslationByKey(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTranslationByKey(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTranslations(): Promise<Array<Translation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTranslations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTranslations();
            return result;
        }
    }
    async getUserById(arg0: bigint): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByPhone(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPhone(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPhone(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPayoutProcessed(arg0: bigint, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markPayoutProcessed(arg0, arg1);
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPayoutProcessed(arg0, arg1);
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async regenerateChampionQR(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateChampionQR(arg0);
                return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateChampionQR(arg0);
            return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: UserRegistrationInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserRegistrationInput_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserRegistrationInput_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectChampion(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectChampion(arg0, arg1);
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectChampion(arg0, arg1);
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: bigint, arg1: UserUpdateInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_UserUpdateInput_n61(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_UserUpdateInput_n61(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateReferralCode(arg0: string): Promise<ChampionCode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateReferralCode(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateReferralCode(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChampionCode_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChampionCode): ChampionCode {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ChampionSelectionMethod_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChampionSelectionMethod): ChampionSelectionMethod {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ConsignmentCheckout_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsignmentCheckout): ConsignmentCheckout {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ConsignmentStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsignmentStatus): ConsignmentStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingStatus): OnboardingStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutLedger_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutLedger): PayoutLedger {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutMethod_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutMethod): PayoutMethod {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutStatus): PayoutStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_PreferredLanguage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PreferredLanguage): PreferredLanguage {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_User_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Translation]): Translation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChampionCode]): ChampionCode | null {
    return value.length === 0 ? null : from_candid_ChampionCode_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    skuCode: string;
    nameEn: string;
    nameFr: string;
    nameKm: string;
    descriptionEn: [] | [string];
    descriptionFr: [] | [string];
    descriptionKm: [] | [string];
    createdAt: bigint;
    baseCostKhr: bigint;
    retailPriceKhr: bigint;
    retailPriceUsd: number;
    commissionRatePercentage: number;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    wholesalePriceKhr: bigint;
    wholesalePriceUsd: number;
    unitMeasurement: string;
    isActive: boolean;
    updatedAt: bigint;
    referralPriceKhr: [] | [bigint];
    referralPriceUsd: [] | [number];
    unitSize: number;
}): {
    id: bigint;
    skuCode: string;
    nameEn: string;
    nameFr: string;
    nameKm: string;
    descriptionEn?: string;
    descriptionFr?: string;
    descriptionKm?: string;
    createdAt: bigint;
    baseCostKhr: bigint;
    retailPriceKhr: bigint;
    retailPriceUsd: number;
    commissionRatePercentage: number;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    wholesalePriceKhr: bigint;
    wholesalePriceUsd: number;
    unitMeasurement: string;
    isActive: boolean;
    updatedAt: bigint;
    referralPriceKhr?: bigint;
    referralPriceUsd?: number;
    unitSize: number;
} {
    return {
        id: value.id,
        skuCode: value.skuCode,
        nameEn: value.nameEn,
        nameFr: value.nameFr,
        nameKm: value.nameKm,
        descriptionEn: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.descriptionEn)),
        descriptionFr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.descriptionFr)),
        descriptionKm: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.descriptionKm)),
        createdAt: value.createdAt,
        baseCostKhr: value.baseCostKhr,
        retailPriceKhr: value.retailPriceKhr,
        retailPriceUsd: value.retailPriceUsd,
        commissionRatePercentage: value.commissionRatePercentage,
        championCommissionKhr: value.championCommissionKhr,
        championCommissionUsd: value.championCommissionUsd,
        wholesalePriceKhr: value.wholesalePriceKhr,
        wholesalePriceUsd: value.wholesalePriceUsd,
        unitMeasurement: value.unitMeasurement,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        referralPriceKhr: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.referralPriceKhr)),
        referralPriceUsd: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.referralPriceUsd)),
        unitSize: value.unitSize
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fullNameEn: string;
    fullNameFr: [] | [string];
    fullNameKm: [] | [string];
    referralCodeActivatedAt: [] | [bigint];
    referredById: [] | [bigint];
    preferredLanguage: _PreferredLanguage;
    qrCodeActivatedAt: [] | [bigint];
    physicalQrCodeId: [] | [string];
    personalReferralCode: [] | [string];
    approvedAt: [] | [bigint];
    createdAt: bigint;
    role: _UserRole;
    isActive: boolean;
    onboardingNotesEn: [] | [string];
    onboardingNotesFr: [] | [string];
    onboardingNotesKm: [] | [string];
    updatedAt: bigint;
    approvedByStaffId: [] | [bigint];
    avatarUrl: [] | [string];
    onboardingStatus: _OnboardingStatus;
    bioEn: [] | [string];
    bioFr: [] | [string];
    bioKm: [] | [string];
    hasPaidForward: boolean;
    phoneNumber: string;
    consignmentInventoryHeld: bigint;
    referredByCode: [] | [string];
    targetMonthlyIncomeKhr: bigint;
    targetMonthlyIncomeUsd: bigint;
}): {
    id: bigint;
    fullNameEn: string;
    fullNameFr?: string;
    fullNameKm?: string;
    referralCodeActivatedAt?: bigint;
    referredById?: bigint;
    preferredLanguage: PreferredLanguage;
    qrCodeActivatedAt?: bigint;
    physicalQrCodeId?: string;
    personalReferralCode?: string;
    approvedAt?: bigint;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    onboardingNotesEn?: string;
    onboardingNotesFr?: string;
    onboardingNotesKm?: string;
    updatedAt: bigint;
    approvedByStaffId?: bigint;
    avatarUrl?: string;
    onboardingStatus: OnboardingStatus;
    bioEn?: string;
    bioFr?: string;
    bioKm?: string;
    hasPaidForward: boolean;
    phoneNumber: string;
    consignmentInventoryHeld: bigint;
    referredByCode?: string;
    targetMonthlyIncomeKhr: bigint;
    targetMonthlyIncomeUsd: bigint;
} {
    return {
        id: value.id,
        fullNameEn: value.fullNameEn,
        fullNameFr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.fullNameFr)),
        fullNameKm: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.fullNameKm)),
        referralCodeActivatedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.referralCodeActivatedAt)),
        referredById: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.referredById)),
        preferredLanguage: from_candid_PreferredLanguage_n25(_uploadFile, _downloadFile, value.preferredLanguage),
        qrCodeActivatedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.qrCodeActivatedAt)),
        physicalQrCodeId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.physicalQrCodeId)),
        personalReferralCode: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.personalReferralCode)),
        approvedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.approvedAt)),
        createdAt: value.createdAt,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        onboardingNotesEn: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.onboardingNotesEn)),
        onboardingNotesFr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.onboardingNotesFr)),
        onboardingNotesKm: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.onboardingNotesKm)),
        updatedAt: value.updatedAt,
        approvedByStaffId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.approvedByStaffId)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.avatarUrl)),
        onboardingStatus: from_candid_OnboardingStatus_n29(_uploadFile, _downloadFile, value.onboardingStatus),
        bioEn: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bioEn)),
        bioFr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bioFr)),
        bioKm: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bioKm)),
        hasPaidForward: value.hasPaidForward,
        phoneNumber: value.phoneNumber,
        consignmentInventoryHeld: value.consignmentInventoryHeld,
        referredByCode: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.referredByCode)),
        targetMonthlyIncomeKhr: value.targetMonthlyIncomeKhr,
        targetMonthlyIncomeUsd: value.targetMonthlyIncomeUsd
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    referralCode: string;
    timesUsedForHotelOrders: bigint;
    createdAt: bigint;
    isActive: boolean;
    timesUsedForChampionReferrals: bigint;
    qrCodeId: string;
    qrCodeImageUrl: [] | [string];
    championId: bigint;
}): {
    id: bigint;
    referralCode: string;
    timesUsedForHotelOrders: bigint;
    createdAt: bigint;
    isActive: boolean;
    timesUsedForChampionReferrals: bigint;
    qrCodeId: string;
    qrCodeImageUrl?: string;
    championId: bigint;
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        timesUsedForHotelOrders: value.timesUsedForHotelOrders,
        createdAt: value.createdAt,
        isActive: value.isActive,
        timesUsedForChampionReferrals: value.timesUsedForChampionReferrals,
        qrCodeId: value.qrCodeId,
        qrCodeImageUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.qrCodeImageUrl)),
        championId: value.championId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ConsignmentStatus;
    staffId: bigint;
    notesEn: [] | [string];
    notesFr: [] | [string];
    notesKm: [] | [string];
    checkedOutAt: bigint;
    productId: bigint;
    quantity: bigint;
    returnedAt: [] | [bigint];
    championId: bigint;
}): {
    id: bigint;
    status: ConsignmentStatus;
    staffId: bigint;
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    checkedOutAt: bigint;
    productId: bigint;
    quantity: bigint;
    returnedAt?: bigint;
    championId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ConsignmentStatus_n37(_uploadFile, _downloadFile, value.status),
        staffId: value.staffId,
        notesEn: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notesEn)),
        notesFr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notesFr)),
        notesKm: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notesKm)),
        checkedOutAt: value.checkedOutAt,
        productId: value.productId,
        quantity: value.quantity,
        returnedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.returnedAt)),
        championId: value.championId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hotelSelectedChampionMethod: _ChampionSelectionMethod;
    qrCodeUsed: [] | [string];
    createdAt: bigint;
    hotelId: bigint;
    orderDate: bigint;
    staffProxyId: [] | [bigint];
    referralCodeUsed: [] | [string];
    updatedAt: bigint;
    khqrReceiptHash: [] | [string];
    khqrPaymentConfirmed: boolean;
    totalAmountKhr: bigint;
    totalAmountUsd: number;
    payoutProcessedDate: [] | [string];
    payoutCycleStartDate: string;
    biweeklyPayoutProcessed: boolean;
    championId: bigint;
    payoutCycleEndDate: string;
}): {
    id: bigint;
    hotelSelectedChampionMethod: ChampionSelectionMethod;
    qrCodeUsed?: string;
    createdAt: bigint;
    hotelId: bigint;
    orderDate: bigint;
    staffProxyId?: bigint;
    referralCodeUsed?: string;
    updatedAt: bigint;
    khqrReceiptHash?: string;
    khqrPaymentConfirmed: boolean;
    totalAmountKhr: bigint;
    totalAmountUsd: number;
    payoutProcessedDate?: string;
    payoutCycleStartDate: string;
    biweeklyPayoutProcessed: boolean;
    championId: bigint;
    payoutCycleEndDate: string;
} {
    return {
        id: value.id,
        hotelSelectedChampionMethod: from_candid_ChampionSelectionMethod_n42(_uploadFile, _downloadFile, value.hotelSelectedChampionMethod),
        qrCodeUsed: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.qrCodeUsed)),
        createdAt: value.createdAt,
        hotelId: value.hotelId,
        orderDate: value.orderDate,
        staffProxyId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.staffProxyId)),
        referralCodeUsed: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.referralCodeUsed)),
        updatedAt: value.updatedAt,
        khqrReceiptHash: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.khqrReceiptHash)),
        khqrPaymentConfirmed: value.khqrPaymentConfirmed,
        totalAmountKhr: value.totalAmountKhr,
        totalAmountUsd: value.totalAmountUsd,
        payoutProcessedDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.payoutProcessedDate)),
        payoutCycleStartDate: value.payoutCycleStartDate,
        biweeklyPayoutProcessed: value.biweeklyPayoutProcessed,
        championId: value.championId,
        payoutCycleEndDate: value.payoutCycleEndDate
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    payoutStatus: _PayoutStatus;
    payoutMethod: _PayoutMethod;
    createdAt: bigint;
    notesEn: [] | [string];
    notesFr: [] | [string];
    notesKm: [] | [string];
    processedByStaffId: [] | [bigint];
    processedAt: [] | [bigint];
    payoutCycleStart: string;
    totalCommissionKhr: bigint;
    totalCommissionUsd: number;
    payoutCycleEnd: string;
    totalOrdersCount: bigint;
    championId: bigint;
}): {
    id: bigint;
    payoutStatus: PayoutStatus;
    payoutMethod: PayoutMethod;
    createdAt: bigint;
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    processedByStaffId?: bigint;
    processedAt?: bigint;
    payoutCycleStart: string;
    totalCommissionKhr: bigint;
    totalCommissionUsd: number;
    payoutCycleEnd: string;
    totalOrdersCount: bigint;
    championId: bigint;
} {
    return {
        id: value.id,
        payoutStatus: from_candid_PayoutStatus_n47(_uploadFile, _downloadFile, value.payoutStatus),
        payoutMethod: from_candid_PayoutMethod_n49(_uploadFile, _downloadFile, value.payoutMethod),
        createdAt: value.createdAt,
        notesEn: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notesEn)),
        notesFr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notesFr)),
        notesKm: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notesKm)),
        processedByStaffId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.processedByStaffId)),
        processedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.processedAt)),
        payoutCycleStart: value.payoutCycleStart,
        totalCommissionKhr: value.totalCommissionKhr,
        totalCommissionUsd: value.totalCommissionUsd,
        payoutCycleEnd: value.payoutCycleEnd,
        totalOrdersCount: value.totalOrdersCount,
        championId: value.championId
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    en: null;
} | {
    fr: null;
} | {
    km: null;
}): PreferredLanguage {
    return "en" in value ? PreferredLanguage.en : "fr" in value ? PreferredLanguage.fr : "km" in value ? PreferredLanguage.km : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: null;
} | {
    staff: null;
} | {
    champion: null;
}): UserRole {
    return "hotel" in value ? UserRole.hotel : "staff" in value ? UserRole.staff : "champion" in value ? UserRole.champion : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): OnboardingStatus {
    return "pending" in value ? OnboardingStatus.pending : "approved" in value ? OnboardingStatus.approved : "rejected" in value ? OnboardingStatus.rejected : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    out: null;
} | {
    sold: null;
} | {
    returned: null;
}): ConsignmentStatus {
    return "out" in value ? ConsignmentStatus.out : "sold" in value ? ConsignmentStatus.sold : "returned" in value ? ConsignmentStatus.returned : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    browsed_list: null;
} | {
    staff_assigned: null;
} | {
    remembered: null;
} | {
    qr_scan: null;
}): ChampionSelectionMethod {
    return "browsed_list" in value ? ChampionSelectionMethod.browsed_list : "staff_assigned" in value ? ChampionSelectionMethod.staff_assigned : "remembered" in value ? ChampionSelectionMethod.remembered : "qr_scan" in value ? ChampionSelectionMethod.qr_scan : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    processed: null;
} | {
    failed: null;
}): PayoutStatus {
    return "pending" in value ? PayoutStatus.pending : "processed" in value ? PayoutStatus.processed : "failed" in value ? PayoutStatus.failed : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    wing: null;
} | {
    bank_transfer: null;
}): PayoutMethod {
    return "cash" in value ? PayoutMethod.cash : "wing" in value ? PayoutMethod.wing : "bank_transfer" in value ? PayoutMethod.bank_transfer : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChampionCode>): Array<ChampionCode> {
    return value.map((x)=>from_candid_ChampionCode_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConsignmentCheckout>): Array<ConsignmentCheckout> {
    return value.map((x)=>from_candid_ConsignmentCheckout_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PayoutLedger>): Array<PayoutLedger> {
    return value.map((x)=>from_candid_PayoutLedger_n45(_uploadFile, _downloadFile, x));
}
function to_candid_ApproveChampionInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApproveChampionInput): _ApproveChampionInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ChampionSelectionMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChampionSelectionMethod): _ChampionSelectionMethod {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ConsignmentInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsignmentInput): _ConsignmentInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_OrderInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PreferredLanguage_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreferredLanguage): _PreferredLanguage {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRegistrationInput_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRegistrationInput): _UserRegistrationInput {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserUpdateInput_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserUpdateInput): _UserUpdateInput {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId: bigint;
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    productId: bigint;
    quantity: bigint;
    championId: bigint;
}): {
    staffId: bigint;
    notesEn: [] | [string];
    notesFr: [] | [string];
    notesKm: [] | [string];
    productId: bigint;
    quantity: bigint;
    championId: bigint;
} {
    return {
        staffId: value.staffId,
        notesEn: value.notesEn ? candid_some(value.notesEn) : candid_none(),
        notesFr: value.notesFr ? candid_some(value.notesFr) : candid_none(),
        notesKm: value.notesKm ? candid_some(value.notesKm) : candid_none(),
        productId: value.productId,
        quantity: value.quantity,
        championId: value.championId
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotelSelectedChampionMethod: ChampionSelectionMethod;
    qrCodeUsed?: string;
    hotelId: bigint;
    staffProxyId?: bigint;
    referralCodeUsed?: string;
    items: Array<OrderItemInput>;
    payoutCycleStartDate: string;
    championId: bigint;
    payoutCycleEndDate: string;
}): {
    hotelSelectedChampionMethod: _ChampionSelectionMethod;
    qrCodeUsed: [] | [string];
    hotelId: bigint;
    staffProxyId: [] | [bigint];
    referralCodeUsed: [] | [string];
    items: Array<_OrderItemInput>;
    payoutCycleStartDate: string;
    championId: bigint;
    payoutCycleEndDate: string;
} {
    return {
        hotelSelectedChampionMethod: to_candid_ChampionSelectionMethod_n13(_uploadFile, _downloadFile, value.hotelSelectedChampionMethod),
        qrCodeUsed: value.qrCodeUsed ? candid_some(value.qrCodeUsed) : candid_none(),
        hotelId: value.hotelId,
        staffProxyId: value.staffProxyId ? candid_some(value.staffProxyId) : candid_none(),
        referralCodeUsed: value.referralCodeUsed ? candid_some(value.referralCodeUsed) : candid_none(),
        items: value.items,
        payoutCycleStartDate: value.payoutCycleStartDate,
        championId: value.championId,
        payoutCycleEndDate: value.payoutCycleEndDate
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skuCode: string;
    nameEn: string;
    nameFr: string;
    nameKm: string;
    descriptionEn?: string;
    descriptionFr?: string;
    descriptionKm?: string;
    baseCostKhr: bigint;
    retailPriceKhr: bigint;
    retailPriceUsd: number;
    commissionRatePercentage: number;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    wholesalePriceKhr: bigint;
    wholesalePriceUsd: number;
    unitMeasurement: string;
    isActive: boolean;
    referralPriceKhr?: bigint;
    referralPriceUsd?: number;
    unitSize: number;
}): {
    skuCode: string;
    nameEn: string;
    nameFr: string;
    nameKm: string;
    descriptionEn: [] | [string];
    descriptionFr: [] | [string];
    descriptionKm: [] | [string];
    baseCostKhr: bigint;
    retailPriceKhr: bigint;
    retailPriceUsd: number;
    commissionRatePercentage: number;
    championCommissionKhr: bigint;
    championCommissionUsd: number;
    wholesalePriceKhr: bigint;
    wholesalePriceUsd: number;
    unitMeasurement: string;
    isActive: boolean;
    referralPriceKhr: [] | [bigint];
    referralPriceUsd: [] | [number];
    unitSize: number;
} {
    return {
        skuCode: value.skuCode,
        nameEn: value.nameEn,
        nameFr: value.nameFr,
        nameKm: value.nameKm,
        descriptionEn: value.descriptionEn ? candid_some(value.descriptionEn) : candid_none(),
        descriptionFr: value.descriptionFr ? candid_some(value.descriptionFr) : candid_none(),
        descriptionKm: value.descriptionKm ? candid_some(value.descriptionKm) : candid_none(),
        baseCostKhr: value.baseCostKhr,
        retailPriceKhr: value.retailPriceKhr,
        retailPriceUsd: value.retailPriceUsd,
        commissionRatePercentage: value.commissionRatePercentage,
        championCommissionKhr: value.championCommissionKhr,
        championCommissionUsd: value.championCommissionUsd,
        wholesalePriceKhr: value.wholesalePriceKhr,
        wholesalePriceUsd: value.wholesalePriceUsd,
        unitMeasurement: value.unitMeasurement,
        isActive: value.isActive,
        referralPriceKhr: value.referralPriceKhr ? candid_some(value.referralPriceKhr) : candid_none(),
        referralPriceUsd: value.referralPriceUsd ? candid_some(value.referralPriceUsd) : candid_none(),
        unitSize: value.unitSize
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullNameEn: string;
    fullNameFr?: string;
    fullNameKm?: string;
    preferredLanguage: PreferredLanguage;
    role: UserRole;
    avatarUrl?: string;
    bioEn?: string;
    bioFr?: string;
    bioKm?: string;
    phoneNumber: string;
    referredByCode?: string;
}): {
    fullNameEn: string;
    fullNameFr: [] | [string];
    fullNameKm: [] | [string];
    preferredLanguage: _PreferredLanguage;
    role: _UserRole;
    avatarUrl: [] | [string];
    bioEn: [] | [string];
    bioFr: [] | [string];
    bioKm: [] | [string];
    phoneNumber: string;
    referredByCode: [] | [string];
} {
    return {
        fullNameEn: value.fullNameEn,
        fullNameFr: value.fullNameFr ? candid_some(value.fullNameFr) : candid_none(),
        fullNameKm: value.fullNameKm ? candid_some(value.fullNameKm) : candid_none(),
        preferredLanguage: to_candid_PreferredLanguage_n57(_uploadFile, _downloadFile, value.preferredLanguage),
        role: to_candid_UserRole_n59(_uploadFile, _downloadFile, value.role),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        bioEn: value.bioEn ? candid_some(value.bioEn) : candid_none(),
        bioFr: value.bioFr ? candid_some(value.bioFr) : candid_none(),
        bioKm: value.bioKm ? candid_some(value.bioKm) : candid_none(),
        phoneNumber: value.phoneNumber,
        referredByCode: value.referredByCode ? candid_some(value.referredByCode) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notesEn?: string;
    notesFr?: string;
    notesKm?: string;
    qrCodeImageUrl?: string;
}): {
    notesEn: [] | [string];
    notesFr: [] | [string];
    notesKm: [] | [string];
    qrCodeImageUrl: [] | [string];
} {
    return {
        notesEn: value.notesEn ? candid_some(value.notesEn) : candid_none(),
        notesFr: value.notesFr ? candid_some(value.notesFr) : candid_none(),
        notesKm: value.notesKm ? candid_some(value.notesKm) : candid_none(),
        qrCodeImageUrl: value.qrCodeImageUrl ? candid_some(value.qrCodeImageUrl) : candid_none()
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullNameEn?: string;
    fullNameFr?: string;
    fullNameKm?: string;
    preferredLanguage?: PreferredLanguage;
    isActive?: boolean;
    avatarUrl?: string;
    bioEn?: string;
    bioFr?: string;
    bioKm?: string;
    hasPaidForward?: boolean;
    targetMonthlyIncomeKhr?: bigint;
    targetMonthlyIncomeUsd?: bigint;
}): {
    fullNameEn: [] | [string];
    fullNameFr: [] | [string];
    fullNameKm: [] | [string];
    preferredLanguage: [] | [_PreferredLanguage];
    isActive: [] | [boolean];
    avatarUrl: [] | [string];
    bioEn: [] | [string];
    bioFr: [] | [string];
    bioKm: [] | [string];
    hasPaidForward: [] | [boolean];
    targetMonthlyIncomeKhr: [] | [bigint];
    targetMonthlyIncomeUsd: [] | [bigint];
} {
    return {
        fullNameEn: value.fullNameEn ? candid_some(value.fullNameEn) : candid_none(),
        fullNameFr: value.fullNameFr ? candid_some(value.fullNameFr) : candid_none(),
        fullNameKm: value.fullNameKm ? candid_some(value.fullNameKm) : candid_none(),
        preferredLanguage: value.preferredLanguage ? candid_some(to_candid_PreferredLanguage_n57(_uploadFile, _downloadFile, value.preferredLanguage)) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        bioEn: value.bioEn ? candid_some(value.bioEn) : candid_none(),
        bioFr: value.bioFr ? candid_some(value.bioFr) : candid_none(),
        bioKm: value.bioKm ? candid_some(value.bioKm) : candid_none(),
        hasPaidForward: value.hasPaidForward ? candid_some(value.hasPaidForward) : candid_none(),
        targetMonthlyIncomeKhr: value.targetMonthlyIncomeKhr ? candid_some(value.targetMonthlyIncomeKhr) : candid_none(),
        targetMonthlyIncomeUsd: value.targetMonthlyIncomeUsd ? candid_some(value.targetMonthlyIncomeUsd) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChampionSelectionMethod): {
    browsed_list: null;
} | {
    staff_assigned: null;
} | {
    remembered: null;
} | {
    qr_scan: null;
} {
    return value == ChampionSelectionMethod.browsed_list ? {
        browsed_list: null
    } : value == ChampionSelectionMethod.staff_assigned ? {
        staff_assigned: null
    } : value == ChampionSelectionMethod.remembered ? {
        remembered: null
    } : value == ChampionSelectionMethod.qr_scan ? {
        qr_scan: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreferredLanguage): {
    en: null;
} | {
    fr: null;
} | {
    km: null;
} {
    return value == PreferredLanguage.en ? {
        en: null
    } : value == PreferredLanguage.fr ? {
        fr: null
    } : value == PreferredLanguage.km ? {
        km: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    hotel: null;
} | {
    staff: null;
} | {
    champion: null;
} {
    return value == UserRole.hotel ? {
        hotel: null
    } : value == UserRole.staff ? {
        staff: null
    } : value == UserRole.champion ? {
        champion: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
